"""
Collection of misc tools
"""

import sys
from typing import Any, Union, List


def normalize_rpyc_return(obj: Any) -> Any:
    """
    Recursively normalize RPyC netrefs and complex objects into pure Python structures.

    This ensures that data coming from an external RPyC gateway is converted into
    safe, local Python types (dict, list, tuple, etc.) before being used by the adapter.

    Parameters
    ----------
    obj : Any
        The object to normalize.

    Returns
    -------
    Any
        The normalized object.
    """
    import rpyc

    # 1. Obtain local copy if it's a netref
    try:
        obj = rpyc.classic.obtain(obj)
    except Exception:
        pass

    # 2. Handle None and scalars
    if obj is None or isinstance(obj, (bool, int, float, str, bytes)):
        return obj

    # 3. Handle namedtuples and objects with an explicit _asdict method defined in their
    #    class hierarchy (not auto-generated by __getattr__, e.g. MagicMock).
    if (
        any("_asdict" in cls.__dict__ for cls in type(obj).__mro__)
        and callable(obj._asdict)
    ):
        return normalize_rpyc_return(obj._asdict())

    # 4. Handle list-like (list, tuple, set)
    if isinstance(obj, (list, tuple, set)):
        normalized_items = [normalize_rpyc_return(item) for item in obj]
        if isinstance(obj, list):
            return normalized_items
        if isinstance(obj, tuple):
            return tuple(normalized_items)
        if isinstance(obj, set):
            # Convert set to list for predictability
            return list(normalized_items)

    # 5. Handle dict-like
    if isinstance(obj, dict):
        return {k: normalize_rpyc_return(v) for k, v in obj.items()}

    # 6. Handle custom objects with public attributes
    if hasattr(obj, "__dict__") and not isinstance(obj, type):
        # Filter out private attributes
        return {
            k: normalize_rpyc_return(v)
            for k, v in obj.__dict__.items()
            if not k.startswith("_")
        }

    return obj


class BadMessage(Exception):
    def __init__(self, text):
        self.text = text


class ClientException(Exception):
    def __init__(self, code, msg, text):
        self.code = code
        self.msg = msg
        self.text = text

def current_fn_name(parent_idx: int = 0) -> str:
    """
    Get the name of the current function.

    Args:
        parent_idx (int): The index of the parent frame. Defaults to 0.

    Returns:
        str: The name of the current function.
    """
    return sys._getframe(1 + parent_idx).f_code.co_name

def parse_mql5_response(text: Union[str, None]) -> Union[str, List[List[str]], None]:
    """
    Parse the MQL5 response text.

    Args:
        text (Union[str, None]): The MQL5 response text.

    Returns:
        Union[str, List[List[str]], None]: The parsed response.
    """
    if text is None:
        return text
    text = text.rstrip(";")
    array = text.split(";")
    result_array = [item.split(",") for item in array]
    if len(array) == 1 and len(result_array[0]) == 1:
        return result_array[0][0]
    return result_array


def get_mql5_period(text: str) -> str:
    """
    Get the MQL5 period string.

    Args:
        text (str): The period text.

    Returns:
        str: The MQL5 period string.
    """
    periods = {
        "M1", "M2", "M3", "M4", "M5", "M6", "M10", "M12", "M15", "M20", "M30",
        "H1", "H2", "H3", "H4", "H6", "H8", "H12", "D1", "W1", "MN1",
    }
    text_upper = text.upper()
    if text_upper in periods:
        return f"PERIOD_{text_upper}"
    return "PERIOD_CURRENT"
